server:
  port: 9527

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ecserver?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: admin
    password: Root@2021

storage:
  home: D:\test\storage